pipeline {
    agent any
    options {
        ansiColor('xterm') // Aktiviert die Farbdarstellung für die gesamte Pipeline
    }
    tools {
        ansible 'ansible_14.1.0'
    }
    stages {
        stage('Checkout Source') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/nufuk/ansible_playbooks.git'
            }
        }
        stage('Run Ansible Playbook') {
            steps {
                ansiblePlaybook( 
                    playbook: 'site.yml'
                )
            }
        }
    }
}
